<?php

declare(strict_types=1);

namespace CdEncoder;

use Symfony\Component\Process\Process;

class Application
{
    private const TRANSCODE_BITRATE = '64k';

    public function index(): void
    {
        $templateData = [
            'message' => '',
            'messageType' => '',
            'downloadUrl' => '',
            'imageUrl' => '',
            'metadata' => [],
            'action' => 'encode' // Default tab
        ];

        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            if (isset($_POST['action']) && $_POST['action'] === 'encode') {
                set_time_limit(120);

                if (isset($_FILES['audio_file']) && $_FILES['audio_file']['error'] === UPLOAD_ERR_OK) {
                    $targetDir = __DIR__ . '/../public/images/';
                    
                    if (!file_exists($targetDir)) {
                        mkdir($targetDir, 0755, true); // Create the directory if it does not exist
                    }


                    // 2. Generate a unique name based on UUID v4
                    $uuid = $this->generateUuidV4();

                    $image = $uuid . '.webp';

                    $outputImage = $targetDir . $image;

                    $transcodedAudioPath = null;

                    try {
                        $transcodedAudioPath = $this->transcodeAudio($_FILES['audio_file']['tmp_name']);

                        $cdEncoder = new CdEncoder($transcodedAudioPath, $outputImage);

                        if ($cdEncoder->encode()) {
                            $templateData['message'] = "Success! The song was encoded at 64 kbps into the CD image.";
                            $templateData['messageType'] = "success";
                            $templateData['imageUrl'] = $image;
                            $templateData['metadata'] = $cdEncoder->getMetadata();
                        } else {
                            $templateData['message'] = "Error while generating the image.";
                            $templateData['messageType'] = "error";
                        }
                    } catch (\Throwable $exception) {
                        $templateData['message'] = $exception->getMessage();
                        $templateData['messageType'] = "error";
                    } finally {
                        if ($transcodedAudioPath !== null && file_exists($transcodedAudioPath)) {
                            unlink($transcodedAudioPath);
                        }
                    }
                } else {
                    $templateData['message'] = "Please upload a valid MP3 file.";
                    $templateData['messageType'] = "error";
                }
            } elseif (isset($_POST['action']) && $_POST['action'] === 'decode') {
                set_time_limit(120);

                $templateData['action'] = 'decode';

                if (isset($_FILES['image_file']) && $_FILES['image_file']['error'] === UPLOAD_ERR_OK) {
                    $targetDir = __DIR__ . '/../public/audio/';
                    
                    if (!file_exists($targetDir)) {
                        mkdir($targetDir, 0755, true); // Create the directory if it does not exist
                    }

                    // 2. Generate a unique name based on UUID v4
                    $uuid = $this->generateUuidV4();

                    $audio = $uuid . '.mp3';

                    $outputAudio = $targetDir . $audio;

                    $cdEncoder = new CdEncoder($outputAudio, $_FILES['image_file']['tmp_name']);
                    
                    $decoded = $cdEncoder->decode();

                    if ($decoded) {
                        $templateData['message'] = "Success! The music was decoded from the image.";
                        $templateData['messageType'] = "success";
                        $templateData['downloadUrl'] = $audio;
                        $templateData['metadata'] = $cdEncoder->getMetadata();
                    } else {
                        $templateData['message'] = "Decoding failed. Make sure the image is a valid lossless WebP generated by this application.";
                        $templateData['messageType'] = "error";
                    }
                } else {
                    $templateData['message'] = "Please upload a valid WebP image.";
                    $templateData['messageType'] = "error";
                }
            }
        }

        echo $this->render('../CdEncoder/templates/ui.php', $templateData);
    }

    private function render(string $filePath, array $variables = []): string
    {
        // 1. Check whether the external file exists
        if (!file_exists($filePath)) {
            //return "Error: Template file was not found.";
        }

        // 2. Extract array keys as variables inside the function
        // Example: ['title' => 'New CD'] becomes $title = 'New CD';
        extract($variables);

        // 3. Start output buffering
        ob_start();

        // 4. Include the external file; PHP replaces the extracted variables
        include $filePath;

        // 5. Store the generated HTML and clear the buffer
        $htmlContent = ob_get_clean();

        // 6. Return the complete HTML with the injected variables
        return (string)$htmlContent;
    }

    private function transcodeAudio(string $inputPath): string
    {
        $outputPath = tempnam(sys_get_temp_dir(), 'cd-encoder-');

        if ($outputPath === false) {
            throw new \RuntimeException("Unable to create the temporary audio file.");
        }

        unlink($outputPath);
        $outputPath .= '.mp3';

        try {
            $process = new Process([
                '/usr/bin/ffmpeg',
                '-y',
                '-i', $inputPath,
                '-map', '0:a:0',
                '-map_metadata', '0',
                '-id3v2_version', '3',
                '-write_id3v1', '1',
                '-codec:a', 'libmp3lame',
                '-b:a', self::TRANSCODE_BITRATE,
                $outputPath,
            ]);
            $process->setTimeout(120);
            $process->run();

            if (!$process->isSuccessful()) {
                throw new \RuntimeException($process->getErrorOutput() ?: $process->getOutput());
            }
        } catch (\Throwable $exception) {
            if (file_exists($outputPath)) {
                unlink($outputPath);
            }

            throw new \RuntimeException(
                "Transcoding to 64 kbps failed. Check the ffmpeg and ffprobe installation and paths.",
                0,
                $exception
            );
        }

        if (!is_readable($outputPath) || filesize($outputPath) === 0) {
            unlink($outputPath);

            throw new \RuntimeException("FFmpeg did not create a valid audio file.");
        }

        return $outputPath;
    }

    private function generateUuidV4(): string
    {
        // Generate 16 cryptographically secure pseudo-random bytes
        $data = random_bytes(16);

        // Set the UUID v4 version bits (0100xxxx)
        $data[6] = chr(ord($data[6]) & 0x0f | 0x40);
        // Set the variant bits (10xxxxxx)
        $data[8] = chr(ord($data[8]) & 0x3f | 0x80);

        // Format the string using the standard 8-4-4-4-12 pattern
        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
    }

    public static function image(string $file): void
    {
        // Sanitize the path for security (allow access only to the images directory)
        $fileName = basename($file);
        $filePath = __DIR__ . '/../public/images/' . $fileName;

        if (file_exists($filePath) && is_file($filePath)) {
            $size = filesize($filePath);

            while (ob_get_level()) {
                ob_end_clean();
            }
            
            // Send standard media streaming headers
            header("Content-Type: image/webp");
            header("Accept-Ranges: bytes");
            header("Content-Disposition: inline");
            header("Content-Length: " . $size);

            // Read and stream the file immediately
            readfile($filePath);
            exit;
        } else {
            http_response_code(404);
        }
    }

    public static function audio(string $file): void
    {
        // Sanitize the path for security (allow access only to the audio directory)
        $fileName = basename($file);
        $filePath = __DIR__ . '/../public/audio/' . $fileName;

        if (file_exists($filePath) && is_file($filePath)) {
            $size = filesize($filePath);

            // Handle Range Requests
            $start = 0;
            $end = $size - 1;
            
            // Handle standard partial requests (Safari/Chrome)
            if (isset($_SERVER['HTTP_RANGE'])) {
                if (preg_match('/bytes=(\d+)-(\d+)?/', $_SERVER['HTTP_RANGE'], $matches)) {
                    $start = intval($matches[1]);
                    if (isset($matches[2])) {
                        $end = intval($matches[2]);
                    }
                }
            }

            $length = $end - $start + 1;

            // Send standard audio streaming headers
            header("Content-Type: audio/mpeg");
            header('Accept-Ranges: bytes');
            header('Content-Range: bytes ' . $start . '-' . $end . '/' . $size);
            header("Content-Disposition: inline");
            header('Content-Length: ' . $length);
            header('HTTP/1.1 206 Partial Content');

            // Read and stream the file immediately
            $fp = fopen($filePath, 'rb');
            fseek($fp, $start);
            echo fread($fp, $length);
            fclose($fp);
            exit;
        } else {
            http_response_code(404);
        }
    }

}
